outputs:
  GPIOE_2: "Injector 1"
  GPIOB_9: "Injector 2"
  GPIOE_1: "Injector 3"
  GPIOE_0: "Injector 4"
  GPIOE_5: "Injector 5"
  GPIOE_4: "Injector 6"
  GPIOB_8: "Injector 7"
  GPIOB_7: "Injector 8" 
  GPIOD_2: "Coil 1"
  GPIOD_1: "Coil 2"
  GPIOD_4: "Coil 3"
  GPIOD_0: "Coil 4"
  GPIOD_3: "Coil 5"
  GPIOD_6: "Coil 6"
  GPIOC_12: "Coil 7"
  GPIOC_9: "Coil 8"
  GPIOG_4: "AC Compressorha"
  GPIOG_5: "Brake Relay"
  GPIOG_6: "Coolant Fan"
  GPIOE_3: "Boost Valve"
  GPIOG_3: "Fuel Pump"
  GPIOG_2: "Alternator Control"
  GPIOD_12: "Thermostat Control"
  GPIOG_12: "VVT Intake"
  GPIOG_13: "VVt Exhaust"

  
  
analog_inputs:
  EFI_ADC_0: "Vbat"
  EFI_ADC_1: "UR Wideband Sensor"
  EFI_ADC_2: "UA Wideband Sensor"
  EFI_ADC_3: "An Temp 1"
  EFI_ADC_4: "Throttle Pedal Sub"
  EFI_ADC_5: "Throttle Pedal Main"
  EFI_ADC_6: "AN Volt 4"
  EFI_ADC_7: "Maf Sensor"
  EFI_ADC_8: "Intake Air Temp"
  EFI_ADC_9: "TPS Sub"
  EFI_ADC_10: "AN Volt 1"
  EFI_ADC_11: "AN Volt 3"
  EFI_ADC_12: "Map Sensor"
  EFI_ADC_13: "Coolant Temp"
  EFI_ADC_14: "AN Volt 2"
  EFI_ADC_15: "TPS Main"
  
  
event_inputs:
  GPIOC_6: "Crank Sensor"
  GPIOA_8: "Cam Sensor"
  GPIOA_15: "Cam Sensor 2"
  GPIOC_7: "Speed Signal"
 

switch_inputs:
  GPIOF_15: "Brake Switch"
  GPIOE_7: "Clutch Switch"
 