
cd ../../..
set PROJECTNAME = MR_Racing
set PROJECT_BOARD=proteus
set PROJECT_CPU=ARCH_STM32F4
set EXTRA_PARAMS=-DHAL_TRIGGER_USE_PAL=TRUE -DHAL_USE_ICU=FALSE -DEFI_VEHICLE_SPEED=FALSE -DEFI_LOGIC_ANALYZER=FALSE
call config/boards/common_make.bat

