outputs:
  GPIOB_7:  "Injector 3Z"
  GPIOB_8:  "Injector 3Y"
  GPIOB_9:  "Injector 3W"
  GPIOC_13: "Injector 2M"
  
  GPIOD_3:  "Injector 3U"
  GPIOD_5:  "Injector 3X"
  GPIOD_7:  "Injector 2N"
  GPIOE_2:  "Injector 3V"
  
  GPIOE_3:  "Injector 3S"
  GPIOE_4:  "Injector 3T"
  GPIOE_5:  "Injector 2O"
  GPIOE_6:  "Injector 2P"

  GPIOC_7:  "Coil 1H"
  GPIOC_9:  "Coil 1F"
  GPIOD_8:  "Coil 1O"
  GPIOD_9:  "Coil 1P"

  GPIOE_8:  "Coil 1L"
  GPIOE_10: "Coil 1I"
  GPIOE_12: "Coil 1M"
  GPIOE_14: "Coil 1G"
  
analog_inputs:
  EFI_ADC_0: "Analog 3O"
  EFI_ADC_1: "Analog 3L"
  EFI_ADC_2: "Analog 3M"
  EFI_ADC_3: "Analog 3J"
  
  EFI_ADC_4: "Analog 3I"
  EFI_ADC_6: "Analog 3H"
  EFI_ADC_7: "Analog 3G"
  EFI_ADC_11: "Analog 3P"
  
  EFI_ADC_12: "Analog 3Q"
  EFI_ADC_13: "Analog 3N"
  EFI_ADC_14: "Analog VBatt"
  EFI_ADC_15: "Analog 3E"
    
  
